apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout-simple
  namespace: openshift-gitops
spec:
  destination:
    namespace: argo-rollout-simple
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./simple
    repoURL: gitea@code.private.opequon.net:opequon_appdev/argo_rollouts_demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
