apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bluegreen

  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bluegreen

  strategy:
    blueGreen: 
      activeService: bluegreen
      previewService: bluegreen-preview
      autoPromotionEnabled: false
